---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundrylondon/bbr-pipeline
    tag: final

inputs:
  - name: bbr-pipeline-tasks-repo
  - name: binary

params:
  SKIP_SSL_VALIDATION: false
  OPSMAN_URL:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:

run:
  path: bbr-pipeline-tasks-repo/tasks/bbr-cleanup-director/task.sh
