---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundrylondon/bbr-pipeline
    tag: final

inputs:
  - name: bbr-pipeline-tasks-repo
  - name: binary
outputs:
  - name: ert-backup-artifact

params:
  SKIP_SSL_VALIDATION: false
  OPSMAN_URL:
  OPSMAN_HOST:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPSMAN_SSH_KEY:

run:
  path: bbr-pipeline-tasks-repo/tasks/bbr-backup-ert/task.sh
