---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundrylondon/bbr-pipeline
    tag: release-candidate

inputs:
- name: bbr-release
outputs:
- name: binary

run:
  path: sh
  args:
  - -c
  - |
    tar -xvf bbr-release/bbr*.tar
    cp releases/bbr binary/
