---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundrylondon/backup-and-restore
    tag: final

inputs:
  - name: bbr-pipeline-tasks-repo
  - name: binary
outputs:
  - name: director-backup-artifact

params:
  SKIP_SSL_VALIDATION: false
  OPSMAN_URL:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPSMAN_PRIVATE_KEY:
  CLIENT_ID:
  CLIENT_SECRET:

run:
  path: bbr-pipeline-tasks-repo/tasks/bbr-backup-director/task.sh
