---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfplatformrecovery/bbr-pcf-pipeline-tasks
    tag: final

inputs:
  - name: bbr-pipeline-tasks-repo
    # Directory containing the bbr executable
  - name: binary

run:
  path: bbr-pipeline-tasks-repo/tasks/bbr-cleanup-pks-clusters/task.sh

params:
  # The Ops Manager URL, e.g. https://pcf.example.com
  OPSMAN_URL:

  # If true, SSL validation will be skipped when connecting to Ops Manager API
  SKIP_SSL_VALIDATION: false

  # Client credentials for Ops Manager API. If empty, user credentials will be used
  CLIENT_ID:
  CLIENT_SECRET:

  # User credentials for Ops Manager API
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:

  # The SSH private key for the Ops Manager VM
  # If provided, a SSH tunnel through the Ops Manager VM is created and used by bbr
  OPSMAN_PRIVATE_KEY:

  # Config NO_PROXY for BOSH cli and OM
  # Setting SET_NO_PROXY: true results in NO_PROXY being exported 
  # with the BOSH Director IP
  SET_NO_PROXY:
  